Script for calculating area and volume of some figures
fioalvsera/geometry pull request #7
Opened 2021-04-09 03:12 UTC by fioalvsera

Script that calculates the area of a square, a rectangle and a circle, and the volume of a cylinder, using functions

2021-04-09 18:48 UTC, jseravalli requested changes
I added two small requests but overall great job!! 🙌🙌🙌

2021-04-09 18:48 UTC, jseravalli commented on index.js
> +switch(shape){
Is there any reason to have 2 switch statements? I think you can merge them and have only one.

2021-04-09 18:48 UTC, jseravalli commented on index.js
> +    let area = (radio * radio) * 3.14
Can you reuse the function to calculate the area of a circle here?

2021-04-09 19:47 UTC, fioalvsera commented on index.js
> +switch(shape){
I'll try to do it

2021-04-09 19:48 UTC, fioalvsera commented on index.js
> +    let area = (radio * radio) * 3.14
I'll try to do it

2021-04-10 20:57 UTC, fioalvsera commented on index.js
> +switch(shape){
I did it, is it ok?

2021-04-10 20:58 UTC, fioalvsera commented on index.js
> +    let area = (radio * radio) * 3.14
I did it, it took me more time but I think I did it. Is it ok? Thank you

2021-04-11 13:11 UTC, jseravalli approved these changes

2021-04-11 13:12 UTC, merged